FROM httpd:alphine
COPY ./SkillsExam/ansible-project/225015765/index.html usr/local/apache2/htdocs/
EXPOSE 80
CMD ["httpd-foreground"]

FROM httpd:alphine
COPY ./SkillsExam/ansible-project/225015765/index.html usr/local/apache2/htdocs
EXPOSE 80
CMD ["httpd-foreground"]

